name: Laravel

on:
  push:
    branches: [ "laravel_main" ]
  pull_request:
    branches: [ "laravel_main" ]

jobs:
  command-run:
    runs-on: ubuntu-latest
    steps:
      - name: Run git pull
        run: git pull origin laravel_main
      - name: Run composer update
        run: composer update

