name: Laravel CI/CD

on:
  push:
    branches:
      - laravel_main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        run: sudo apt install -y php
      - name: Install Composer
        run: composer install
      - name: Migrate the database
        run: php artisan migrate
      - name: Seed the database
        run: php artisan db:seed
      - name: Update Composer
        run: composer update
