name: Laravel CI/CD

on:
  push:
    branches:
      - laravel_main

jobs:
  test:
    runs-on: ubuntu-latest

    composer-update:
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.0'

        - name: Copy .env
          run: cp .env.example .env

        - name: Install Composer dependencies
          run: composer install --no-scripts --no-progress --prefer-dist

        - name: Generate application key
          run: php artisan key:generate

        - name: Run database migrations
          env:
            DB_HOST: localhost
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: password
          run: php artisan migrate --force

        - name: Run tests
          run: vendor/bin/phpunit
