name: Laravel

on:
  push:
    branches: [ "laravel_main" ]
  pull_request:
    branches: [ "laravel_main" ]

jobs:
  composer-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest
      - name: Update Composer dependencies
        run: composer update --no-progress --no-suggest

  database-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest
      - name: Configure MySQL credentials
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=password" >> .env
      - name: Display Environment Variables
        run: env
      - name: Test Database Connection
        run: php artisan db:test
      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-client
      - name: Run migrations
        run: php artisan migrate --force

  command-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Run artisan db:seed
        run: |
          php artisan db:seed 
          php artisan cache:clear
           
      - name: Run git pull
        run: git pull origin laravel_main
      - name: Run composer update
        run: composer update
      - name: Run artisan migrate
        run: php artisan migrate
        #php artisan migrate

  npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      #- name: Pull latest changes
        #run: git pull origin laravel_main
